{
 "title": "Database",
 "tags": [ "Juneo" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Database Read Rate",
   "type": "timeseries",
   "description": "Database read rate. Note that these reads may be from caches and not from disk.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(juneomcn_meterdb_size{chain=\"all\", method=~\"has|get|iterator_next\"}[5m]))",
     "legendFormat": "Bytes Read {{node_id}}"
    }
   ]
  },
  {
   "title": "Database Write Rate",
   "type": "timeseries",
   "description": "Database write rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(juneomcn_meterdb_size{chain=\"all\", method=~\"put|delete|batch_write\"}[5m]))",
     "legendFormat": "Bytes Written {{node_id}}"
    }
   ]
  },
  {
   "title": "Total Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second across all chains",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(juneomcn_meterdb_calls{chain=\"all\", job=\"juneogo\"}[5m])",
     "legendFormat": "{{ method }} {{node_id}}"
    }
   ]
  },
  {
   "title": "Total Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(juneomcn_meterdb_duration{chain=\"all\", job=\"juneogo\"}[5m])/increase(juneomcn_meterdb_calls{chain=\"all\", job=\"juneogo\"}[5m])",
     "legendFormat": "{{ method }} {{node_id}}"
    }
   ]
  },
  {
   "title": "JVM-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second on JVM-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(juneomcn_meterdb_calls{chain=\"JVM\", job=\"juneogo\"}[5m])",
     "legendFormat": "{{ method }} {{node_id}}"
    }
   ]
  },
  {
   "title": "JVM-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on JVM-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(juneomcn_meterdb_duration{chain=\"JVM\", job=\"juneogo\"}[5m])/increase(juneomcn_meterdb_calls{chain=\"JVM\", job=\"juneogo\"}[5m])",
     "legendFormat": "{{ method }} {{node_id}}"
    }
   ]
  },
  {
   "title": "P-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second on P-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(juneomcn_meterdb_calls{chain=\"P\", job=\"juneogo\"}[5m])",
     "legendFormat": "{{ method }} {{node_id}}"
    }
   ]
  },
  {
   "title": "P-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on P-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(juneomcn_meterdb_duration{chain=\"P\", job=\"juneogo\"}[5m])/increase(juneomcn_meterdb_calls{chain=\"P\", job=\"juneogo\"}[5m])",
     "legendFormat": "{{ method }} {{node_id}}"
    }
   ]
  },
  {
   "title": "JUNE-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second across all chains",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(juneomcn_meterdb_calls{chain=\"JUNE\", job=\"juneogo\"}[5m])",
     "legendFormat": "{{ method }} {{node_id}}"
    }
   ]
  },
  {
   "title": "JUNE-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on JUNE-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(juneomcn_meterdb_duration{chain=\"JUNE\", job=\"juneogo\"}[5m])/increase(juneomcn_meterdb_calls{chain=\"JUNE\", job=\"juneogo\"}[5m])",
     "legendFormat": "{{ method }} {{node_id}}"
    }
   ]
  }
 ]
}